
#define PI                      ( 3.14159265359)

#define SYS_SMALL_PISTON_DIAMETER         ( 2.25f )
#define SYS_SMALL_PISTON_MAX_LENGTH       ( 6.00f )
#define SYS_LARGE_PISTON_DIAMETER         ( 4.50f ) 
#define SYS_LARGE_PISTON_MAX_LENGTH       ( 6.0f )
#define SYS_HOUSING_DIAMETER                ( 4.88f )
#define SYS_HOUSING_LENGTH                  ( 35.0f )


#define SMALL_PISTON_DIAMETER     (SYS_SMALL_PISTON_DIAMETER)
#define SMALL_PISTON_MAX_LENGTH   (SYS_SMALL_PISTON_MAX_LENGTH)
#define SMALL_PISTON_MAX_VOLUME   (SMALL_PISTON_DIAMETER * PI * SMALL_PISTON_MAX_LENGTH)
#define LARGE_PISTON_DIAMETER     (SYS_LARGE_PISTON_DIAMETER)
#define LARGE_PISTON_MAX_LENGTH   (SYS_LARGE_PISTON_MAX_LENGTH)
#define LARGE_PISTON_MAX_VOLUME   (LARGE_PISTON_DIAMETER * PI * LARGE_PISTON_MAX_LENGTH)
#define HOUSING_DIAMETER          (SYS_HOUSING_DIAMETER)
#define HOUSING_LENGTH            (SYS_HOUSING_LENGTH)
#define HOUSING_VOLUME            (HOUSING_DIAMETER * PI * HOUSING_LENGTH)
#define SYSTEM_MAX_VOLUME         (HOUSING_VOLUME + SMALL_PISTON_MAX_VOLUME + LARGE_PISTON_MAX_VOLUME + 0.01)
#define SYSTEM_MIN_VOLUME         (HOUSING_VOLUME - 0.01)
#define SYSTEM_MIN_LENGTH         (0.0f)
#define SYSTEM_MAX_LENGTH         (SMALL_PISTON_MAX_LENGTH + LARGE_PISTON_MAX_LENGTH)

#define DRAG_PLATE_DIAMETER         ( 8.0f )
#define DRAG_PLATE_RADIUS           ( DRAG_PLATE_DIAMETER /2 )
#define DRAG_PLATE_AREA             ( PI * DRAG_PLATE_DIAMETER * DRAG_PLATE_DIAMETER )

#define SYSTEM_WEIGHT_EST           ( 25.0 )
#define SYSTEM_CROSSSECTION_AREA    ( DRAG_PLATE_AREA )

#define CYLINDER_DRAG_COEFF         ( 0.81 )

#define SYSTEM_DENSITY_SEAWATER     ( 1033.0 )
#define SYSTEM_VOLUME_MIN           ( HOUSING_VOLUME)
#define SYSTEM_VOLUME_MAX           ( HOUSING_VOLUME + SMALL_PISTON_MAX_VOLUME )
#define SYSTEM_VOLUME_RESERVE       ( LARGE_PISTON_MAX_VOLUME )
#define SYSTEM_NEUTRAL_BUOYANCY     ( 1025 ) 
#define SYSTEM_RISE_RATE_MAX        ( 0.075 )
#define SYSTEM_RISE_RATE_SETPOINT   ( 0.100 )
#define SYSTEM_RISE_RATE_MIN        ( 0.125 )
#define SYSTEM_FALL_RATE_MAX        ( 0.125 )
#define SYSTEM_FALL_RATE_MIN        ( 0.075 )
#define SYSTEM_FALL_RATE_SETPOINT   ( 0.100 )


#define SYSTEM_PROFILER_PARK_DEPTH              ( 30 )
#define SYSTEM_PROFILER_PARK_DEPTH_ERR          ( 2 ) 
#define SYSTEM_PROFILER_PARK_DURATION_MIN       ( 10 )
#define SYSTEM_PROFILER_PARK_DURATION_SEC       ( SYSTEM_PROFILER_PARK_DURATION_MIN * 60 )
#define SYSTEM_PROFILER_PARK_RATE               ( 1/60 )

#define SYSTEM_PROFILER_PROFILE_DEPTH           ( 40 )
#define SYSTEM_PROFILER_PROFILE_DEPTH_ERR       ( 1.0 )
#define SYSTEM_PROFILER_PROFILE_RATE            ( 1 )
#define SYSTEM_PROFILER_PROFILE_OFF_DEPTH       ( 1.0 )
#define SYSTEM_PROFILER_PROFILE_EXTRA_OOMPH     ( true )


#define SYSTEM_CRUSH_LIMIT_DEPTH                ( 220.0 )